apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd   # The controller manifest itself registers in argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 61.3.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring # Isolated target workload destination!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Directs Argo CD to create the namespace automatically
      prune: true
      selfHeal: true
    createNamespace: true
